/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package öğrencikayıt;

/**
 *
 * @author Yakup
 */
public class AnaMenü extends javax.swing.JFrame {

    /**
     * Creates new form AnaMenü
     */
    public AnaMenü() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anaMenüPanel = new javax.swing.JPanel();
        kayıtEkleButton = new javax.swing.JButton();
        kayıtlarıListeleButton = new javax.swing.JButton();
        kayıtDüzenleButton = new javax.swing.JButton();
        kayıtAraButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Öğrenci Kayıt Ana Menüsü");
        setResizable(false);

        anaMenüPanel.setBackground(new java.awt.Color(0, 180, 180));

        kayıtEkleButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        kayıtEkleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Icons/kelimeEkle.png"))); // NOI18N
        kayıtEkleButton.setText("Kayıt Ekle");
        kayıtEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayıtEkleButtonActionPerformed(evt);
            }
        });

        kayıtlarıListeleButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        kayıtlarıListeleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Icons/liste.png"))); // NOI18N
        kayıtlarıListeleButton.setText("Kayıtları Listele");
        kayıtlarıListeleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayıtlarıListeleButtonActionPerformed(evt);
            }
        });

        kayıtDüzenleButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        kayıtDüzenleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Icons/düzenle.png"))); // NOI18N
        kayıtDüzenleButton.setText("Kayıt Düzenle");
        kayıtDüzenleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayıtDüzenleButtonActionPerformed(evt);
            }
        });

        kayıtAraButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        kayıtAraButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project Icons/ara.png"))); // NOI18N
        kayıtAraButton.setText("Kayıt Ara");
        kayıtAraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayıtAraButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout anaMenüPanelLayout = new javax.swing.GroupLayout(anaMenüPanel);
        anaMenüPanel.setLayout(anaMenüPanelLayout);
        anaMenüPanelLayout.setHorizontalGroup(
            anaMenüPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anaMenüPanelLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(anaMenüPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kayıtlarıListeleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kayıtEkleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kayıtDüzenleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kayıtAraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(177, 177, 177))
        );
        anaMenüPanelLayout.setVerticalGroup(
            anaMenüPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anaMenüPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(kayıtEkleButton)
                .addGap(28, 28, 28)
                .addComponent(kayıtlarıListeleButton)
                .addGap(26, 26, 26)
                .addComponent(kayıtAraButton)
                .addGap(32, 32, 32)
                .addComponent(kayıtDüzenleButton)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anaMenüPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anaMenüPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kayıtEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayıtEkleButtonActionPerformed
        // TODO add your handling code here:
        new KayıtEkle().setVisible(true);

    }//GEN-LAST:event_kayıtEkleButtonActionPerformed

    private void kayıtlarıListeleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayıtlarıListeleButtonActionPerformed
        // TODO add your handling code here:
        new KayıtlarıListele().setVisible(true);
    }//GEN-LAST:event_kayıtlarıListeleButtonActionPerformed

    private void kayıtDüzenleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayıtDüzenleButtonActionPerformed
        // TODO add your handling code here:
        new KayıtDüzenleveyaSil().setVisible(true);
    }//GEN-LAST:event_kayıtDüzenleButtonActionPerformed

    private void kayıtAraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayıtAraButtonActionPerformed
        // TODO add your handling code here:
        new ÖğrenciAra().setVisible(true);
    }//GEN-LAST:event_kayıtAraButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaMenü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaMenü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaMenü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaMenü.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaMenü().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel anaMenüPanel;
    private javax.swing.JButton kayıtAraButton;
    private javax.swing.JButton kayıtDüzenleButton;
    private javax.swing.JButton kayıtEkleButton;
    private javax.swing.JButton kayıtlarıListeleButton;
    // End of variables declaration//GEN-END:variables
}
