/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package öğrencikayıt;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Yakup
 */
public class ÖğrenciAra extends javax.swing.JFrame {

    ArrayList<Öğrenci> öğrenciler;

    /**
     * Creates new form ÖğrenciAra
     */
    public ÖğrenciAra() {
        initComponents();

        öğrenciler = new ArrayList<Öğrenci>();
        arrayListiDoldur();
        Object[][] veri = new Object[öğrenciler.size()][8];

        for (int i = 0; i < öğrenciler.size(); i++) {
            veri[i][0] = öğrenciler.get(i).ad;
            veri[i][1] = öğrenciler.get(i).soyad;
            veri[i][2] = öğrenciler.get(i).öğrenciNo;
            veri[i][3] = öğrenciler.get(i).bölüm;
            veri[i][4] = öğrenciler.get(i).cinsiyet;
            veri[i][5] = öğrenciler.get(i).doğumYeri;
            veri[i][6] = öğrenciler.get(i).yaş;
            veri[i][7] = öğrenciler.get(i).telefonNo;

        }

        kayıtTable.setModel(new javax.swing.table.DefaultTableModel(
                veri,
                new String[]{
                    "Ad", "Soyad", "Öğrenci Numarası", "Bölümü", "Cinsiyet", "Doğum Yeri", "Yaş", "Telefon Numarası"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        kayıtTable.setAutoCreateRowSorter(true);
    }

    public void arrayListiDoldur() {
        try {
            FileInputStream file = new FileInputStream("ogrenciler.dat");
            ObjectInput inputFile = new ObjectInputStream(file);

            boolean dosyaSonu = false;
            while (!dosyaSonu) {
                try {
                    öğrenciler.add((Öğrenci) inputFile.readObject());
                } catch (EOFException e) {
                    dosyaSonu = true;
                } catch (Exception f) {
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            inputFile.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kayıtAraPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kayıtTable = new javax.swing.JTable();
        öğrenciAraLabel = new javax.swing.JLabel();
        öğrenciAraTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Öğrenci Ara");
        setResizable(false);

        kayıtAraPanel.setBackground(new java.awt.Color(0, 180, 180));

        kayıtTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ad", "Soyad", "Öğrenci Numarası", "Bölümü", "Cinsiyet", "Doğum Yeri", "Yaş", "Telefon Numarası"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(kayıtTable);

        öğrenciAraLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        öğrenciAraLabel.setText("Öğrenci Ara:");

        öğrenciAraTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        öğrenciAraTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                öğrenciAraTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout kayıtAraPanelLayout = new javax.swing.GroupLayout(kayıtAraPanel);
        kayıtAraPanel.setLayout(kayıtAraPanelLayout);
        kayıtAraPanelLayout.setHorizontalGroup(
            kayıtAraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kayıtAraPanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(kayıtAraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kayıtAraPanelLayout.createSequentialGroup()
                        .addComponent(öğrenciAraLabel)
                        .addGap(18, 18, 18)
                        .addComponent(öğrenciAraTextField))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        kayıtAraPanelLayout.setVerticalGroup(
            kayıtAraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kayıtAraPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(kayıtAraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(öğrenciAraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(öğrenciAraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kayıtAraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kayıtAraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void öğrenciAraTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_öğrenciAraTextFieldKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) kayıtTable.getModel();
        String search = öğrenciAraTextField.getText().toUpperCase();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        kayıtTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_öğrenciAraTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÖğrenciAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÖğrenciAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÖğrenciAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÖğrenciAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ÖğrenciAra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kayıtAraPanel;
    private javax.swing.JTable kayıtTable;
    private javax.swing.JLabel öğrenciAraLabel;
    private javax.swing.JTextField öğrenciAraTextField;
    // End of variables declaration//GEN-END:variables
}
